### ISSUE TITLE
express is not installing

### ISSUE THREAD

**Issue by ecabrera1** [siyangbi/docker-nginx-node-postgres-elasticsearch#1]
ode2_1    | module.js:340
node2_1    |     throw err;
node2_1    |           ^
node2_1    | Error: Cannot find module '_express_'
node2_1    |     at Function.Module._resolveFilename (module.js:338:15)
node2_1    |     at Function.Module._load (module.js:280:25)
node2_1    |     at Module.require (module.js:364:17)
node2_1    |     at require (module.js:380:17)
node2_1    |     at Object.<anonymous> (/src/index.js:1:77)
node2_1    |     at Module._compile (module.js:456:26)
node2_1    |     at Object.Module._extensions..js (module.js:474:10)
node2_1    |     at Module.load (module.js:356:32)
node2_1    |     at Function.Module._load (module.js:312:12)
node2_1    |     at Function.Module.runMain (module.js:497:10)
node2_1    | 27 May 18:42:42 - [nodemon] app crashed - waiting for file changes before starting...

**Comment by siyangbi** [comment]
Since I use external volume  for development, you have to run npm install in the node folder
